import {
  AirVent,
  Bath,
  Bed,
  Book,
  Box,
  Car,
  ChefHat,
  Coffee,
  Cog,
  DoorOpen,
  Fan,
  Flame,
  Gamepad2,
  Heart,
  Home,
  Key,
  Lock,
  type LucideIcon,
  Mountain,
  Music2,
  Plug,
  Shirt,
  ShowerHead,
  Sofa,
  Sun,
  Table2,
  Timer,
  Tv,
  Utensils,
  Wifi,
  Wine
} from "lucide-react"

const amenityIconMap = new Map<string, LucideIcon>([
  ["Garden view", Mountain],
  ["Valley view", Mountain],
  ["Hair dryer", Fan],
  ["Cleaning products", Cog],
  ["Shampoo", Bath],
  ["Conditioner", Bath],
  ["Body soap", Bath],
  ["Hot water", ShowerHead],
  ["Washer", Cog],
  ["Dryer", Cog],
  ["Essentials", Heart],
  ["Hangers", Shirt],
  ["Bed linens", Bed],
  ["Extra pillows and blankets", Bed],
  ["Iron", Cog],
  ["Drying rack for clothing", Shirt],
  ["Safe", Lock],
  ["Clothing storage", Box],
  ["TV", Tv],
  ["TV with standard cable", Tv],
  ["Sound system", Music2],
  ["Books and reading material", Book],
  ["Crib", Bed],
  ["Pack 'n play/Travel crib", Bed],
  ["High chair", Bed],
  ["Children's dinnerware", Utensils],
  ["Baby safety gates", Lock],
  ["Air conditioning", AirVent],
  ["Indoor fireplace", Flame],
  ["Central heating", Flame],
  ["Heating", Flame],
  ["Smoke alarm", Flame],
  ["Carbon monoxide alarm", Flame],
  ["Fire extinguisher", Flame],
  ["First aid kit", Heart],
  ["Wifi", Wifi],
  ["Dedicated workspace", Table2],
  ["Kitchen", ChefHat],
  ["Refrigerator", Box],
  ["Microwave", Cog],
  ["Cooking basics", Utensils],
  ["Dishes and silverware", Utensils],
  ["Freezer", Box],
  ["Dishwasher", Cog],
  ["Stove", Flame],
  ["Oven", Flame],
  ["Hot water kettle", Coffee],
  ["Coffee maker", Coffee],
  ["Coffee maker: drip coffee maker", Coffee],
  ["Wine glasses", Wine],
  ["Toaster", Flame],
  ["Dining table", Table2],
  ["Private entrance", DoorOpen],
  ["Fire pit", Flame],
  ["Free parking on premises", Car],
  ["Free street parking", Car],
  ["Free carport on premises", Car],
  ["Private sauna", Flame],
  ["EV charger", Plug],
  ["Long term stays allowed", Timer],
  ["Self check-in", Key],
  ["Smart lock", Lock],
  ["Shared patio or balcony", Sun],
  ["Backyard", Sun],
  ["Outdoor furniture", Sofa],
  ["Free parking on premises", Car],
  ["Free street parking", Car],
  ["Luggage dropoff allowed", Home],
  ["Mountain view", Mountain],
  ["Bathtub", Bath],
  ["Outdoor shower", ShowerHead],
  ["Shower gel", Bath],
  ["Free washer – In unit", Cog],
  ["Free dryer – In unit", Cog],
  ["Room-darkening shades", Sun],
  ["Mosquito net", Bed],
  ["Game console", Gamepad2],
  ["Arcade games", Gamepad2],
  ["Movie theater", Tv],
  ["Theme room", Home],
  ["Life size games", Gamepad2],
  ["Crib - always at the listing", Bed],
  ["Children's books and toys", Book],
  ["Central air conditioning", AirVent],
  ["Indoor fireplace: gas", Flame],
  ["Ceiling fan", Fan],
  ["Portable fans", Fan],
  ["Exterior security cameras on property", Lock],
  ["ZLINE stainless steel gas stove", Flame],
  ["Baking sheet", ChefHat],
  ["Blender", ChefHat],
  ["Barbecue utensils", Utensils],
  ["Coffee", Coffee],
  ["Laundromat nearby", Cog],
  ["Patio or balcony", Sun],
  ["Outdoor kitchen", ChefHat],
  ["BBQ grill", Flame],
  ["Private hot tub", Bath]
])

export function getAmenityIcon(amenity: string): LucideIcon {
  return amenityIconMap.get(amenity) ?? Cog
}
