import type { LucideIcon } from "lucide-react"
import {
  Bath,
  Bed,
  Book,
  Car,
  ChefHat,
  Coffee,
  Cog,
  Fan,
  Flame,
  Heart,
  Home,
  Lock,
  Mountain,
  Music2,
  Shirt,
  ShowerHead,
  Sofa,
  Sun,
  Table2,
  Tv,
  Utensils,
  Wifi,
  Wine,
  Box
} from "lucide-react"

const amenityIconMap = new Map<string, LucideIcon>([
  ["Garden view", Mountain],
  ["Valley view", Mountain],
  ["Hair dryer", Fan],
  ["Cleaning products", Cog],
  ["Shampoo", Bath],
  ["Conditioner", Bath],
  ["Body soap", Bath],
  ["Hot water", ShowerHead],
  ["Shower gel", Bath],
  ["Washer", Cog],
  ["Dryer", Cog],
  ["Essentials", Heart],
  ["Hangers", Shirt],
  ["Bed linens", Bed],
  ["Extra pillows and blankets", Bed],
  ["Iron", Cog],
  ["Safe", Lock],
  ["Clothing storage: closet and dresser", Shirt],
  ["TV with standard cable", Tv],
  ["Sound system with Bluetooth and aux", Music2],
  ["Books and reading material", Book],
  ["Crib", Bed],
  ["Pack 'n play/Travel crib", Bed],
  ["Heating", Flame],
  ["Smoke alarm", Flame],
  ["Carbon monoxide alarm", Flame],
  ["First aid kit", Heart],
  ["Wifi", Wifi],
  ["Kitchen", ChefHat],
  ["Refrigerator", Box],
  ["Microwave", Cog],
  ["Cooking basics", Utensils],
  ["Dishes and silverware", Utensils],
  ["Freezer", Box],
  ["Dishwasher", Cog],
  ["Stove", Flame],
  ["Oven", Flame],
  ["Coffee maker", Coffee],
  ["Wine glasses", Wine],
  ["Toaster", Flame],
  ["Dining table", Table2],
  ["Coffee", Coffee],
  ["Shared patio or balcony", Sun],
  ["Backyard", Sun],
  ["Outdoor furniture", Sofa],
  ["Free parking on premises", Car],
  ["Free street parking", Car],
  ["Luggage dropoff allowed", Home]
])

export function getAmenityIcon(amenity: string): LucideIcon {
  return amenityIconMap.get(amenity) ?? Cog
}
